#!/bin/sh
nmcli con mod "Wired connection 1" ipv4.address 192.168.1.1/24 ipv4.method manual
hostname CHANGEME-HOSTNAME
ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -q -N '' && mv /root/.ssh/id_rsa /root/.ssh/authorized_keys